WEB2019Apr_P02_Team1/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace WEB2019Apr_P02_Team1.Models
{
    public class Student
    {
        public int StudentID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(50)]
        public string Course { get; set; }

        [StringLength(250)]
        public string Photo { get; set; }

        [StringLength(3000)]
        public string Description { get; set; }

        [StringLength(3000)]
        public string Achievement { get; set; }

        [StringLength(255)]
        public string ExternalLink { get; set; }

        [Display(Name = "Email Address")]
        [Required]
        [StringLength(50)]
        [EmailAddress]
        //[ValidateEmailExists(ErrorMessage = "Email address already exists!")]
        public string EmailAddr { get; set; }

        [StringLength(255)]
        public string Password { get; set; }

        [Required]
        public int MentorID { get; set; }

        [Display(Name = "Upload new picture")]
        public IFormFile FileToUpload { get; set; }
    }
}

WEB2019Apr_P02_Team1/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using WEB2019Apr_P02_Team1.DAL;
using WEB2019Apr_P02_Team1.Models;
using System.IO;

namespace WEB2019Apr_P02_Team1.Controllers
{
    public class ProjectController : Controller
    {
        public IActionResult Index()
        {
            int? id = HttpContext.Session.GetInt32("ID");
            string session = HttpContext.Session.GetString("Role");
            if (id == null || session != "Student")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();

        }

        private ProjectDAL ProjectContext = new ProjectDAL();
        private StudentDAL StudentContext = new StudentDAL();


        public ActionResult Create()
        {
            int? id = HttpContext.Session.GetInt32("ID");
            string session = HttpContext.Session.GetString("Role");
            if (id == null || session != "Student")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        //Creating the portfolio
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project)
        {
            if (ModelState.IsValid)
            {
                int? id = HttpContext.Session.GetInt32("ID");

                int projectId = ProjectContext.Create(project);
                Student student = StudentContext.Get(Convert.ToInt32(id));
                ProjectMember member = new ProjectMember
                {
                    ProjectID = projectId,
                    StudentID = student.StudentID,
                    Role = "Leader"
                };
                ProjectContext.AddMember(member);
                return RedirectToAction("ViewProject");
            }

            return View(project);
            
        }

        public ActionResult ViewProject()
        {
            int? id = HttpContext.Session.GetInt32("ID");
            string session = HttpContext.Session.GetString("Role");
            if (id == null || session != "Student")
            {
                return RedirectToAction("Index", "Home");
            }
            //Getting all of the projects of that student
            List<Project> ProjectList = ProjectContext.GetAllProjects(id);
            if (ProjectList.Count == 0 || ProjectList == null)
            {
                TempData["error"] = "No projects found, create one by clicking on the create project button";
                return View(ProjectList);
            }
            return View(ProjectList);
        }


        //Getting the details of the project
        public ActionResult DetailProject(int? id)
        {
            string session = HttpContext.Session.GetString("Role");
            if (id == null || ProjectContext.GetProject(id.Value) == null)
            {
                return RedirectToAction("Index", "Home");
            }
            EditProjectViewModel view = ProjectContext.GetMembersTest(id.Value);
            ViewData["role"] = session;
            return View(view);
        }


        public ActionResult UpdateNew(int? id)
        {
            int? idview = HttpContext.Session.GetInt32("ID");
            string session = HttpContext.Session.GetString("Role");

            if (idview == null || session != "Student" || id == null)
            {   
                return RedirectToAction("Index", "Home");
            }

            //var (studentList, memberDetail, project, RemainingStudents) = GetDetailsMember(id.Value);
            EditProjectViewModel view = ProjectContext.GetMembersTest(id.Value);
            //not letting other from viewing the content
            //make this into a function 
            List<int> ids = new List<int>();
            foreach (var item in view.MemberDetails)
            {
                ids.Add(item.StudentID);
            }
            if (!ids.Contains(Convert.ToInt32(idview)))
            {
              return RedirectToAction("Index", "Home");
            }

            List<Student> students = StudentContext.GetAllStudents();
            List<Student> nonMembersDetails = GetNonMembers(students, view.MemberDetails);

            //converts all non-members to members
            List<ProjectMember> convertedAllMembers = ConvertAllToProjectMember(nonMembersDetails, view.Members, view.Project);
            // however only people selected will be added/removed in the end
            EditProjectViewModel edit = new EditProjectViewModel
            {
                Project = view.Project,
                Members = convertedAllMembers,
                //Getting students who are not in the group to be added as options
                MemberDetails = StudentContext.GetAllStudents()
               
            };
            return View(edit);
        }

        [HttpPost]
        public ActionResult UpdateNew(EditProjectViewModel edit)
        {

            if (ModelState.IsValid)
            {
                List<ProjectMember> members = ProjectContext.GetMembers(edit.Project.ProjectId);
                ProjectContext.Update(edit.Project);
                foreach (var item in edit.Members)
                {
                    int count = 0;
                    if (item.Check)
                    {
                        foreach (var mem in members)
                        {
                            if (mem.StudentID == item.StudentID)
                            {
                                count += 1;
                                //remove all of the spaces so that we can check if the item is a member
                                item.Role = item.Role.Replace(" ", string.Empty);
                                if (item.Role == "Member")
                                {
                                    ProjectContext.Delete(item.StudentID, edit.Project.ProjectId);
                                }
                            }
                        }

                        if (count == 0)
                        {
                            item.Role = "Member";
                            ProjectContext.AddMember(item);
                        }
                    }
                }
                return RedirectToAction("ViewProject");
            }
            else
            {

                EditProjectViewModel view = ProjectContext.GetMembersTest(edit.Project.ProjectId);
                List<Student> students = StudentContext.GetAllStudents();
                List<Student> nonMembersDetails = GetNonMembers(students, view.MemberDetails);

                //converts all non-members to members
                List<ProjectMember> convertedAllMembers = ConvertAllToProjectMember(nonMembersDetails, view.Members, view.Project);

                // however only people selected will be added/removed in the end
                EditProjectViewModel edit1 = new EditProjectViewModel
                {
                    Project = view.Project,
                    Members = convertedAllMembers,
                    //Getting students who are not in the group to be added as options
                    MemberDetails = StudentContext.GetAllStudents()

                };

                TempData["Error"] = "Invalid input";
                //edit1 was here
                return View(edit1);
            }
        }

        public ActionResult Upload(int? id)
        {   
            //make this into a function too
            int? idview = HttpContext.Session.GetInt32("ID");
            string session = HttpContext.Session.GetString("Role");

            if (idview == null || session != "Student" || id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            EditProjectViewModel view = ProjectContext.GetMembersTest(id.Value);

            //not letting other from viewing the content
            List<int> ids = new List<int>();
            foreach (var item in view.MemberDetails)
            {
                ids.Add(item.StudentID);
            }
            if (!ids.Contains(Convert.ToInt32(idview)))
            {
                return RedirectToAction("Index", "Home");
            }

            ProjectViewModel convertedProject = ConvertProject(view.Project);
            return View(convertedProject);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(ProjectViewModel convertedProject)
        {
            //If the user does not have any upload and clicks on upload 
            //validate
            if (convertedProject.FileToUpload != null
               && convertedProject.FileToUpload.Length > 0) 
            {
                if (ModelState.IsValid)
                {
                    string fileExtension =
                            Path.GetExtension(convertedProject.FileToUpload.FileName);


                    if (!CheckExtension(fileExtension))
                    {
                        ViewData["Message"] = "Wrong file type, please use one of the following (.jpg, .jpeg, .jfif, .pjpeg, .pjp)";
                        Project project = ProjectContext.GetProject(convertedProject.ProjectId);
                        convertedProject.ProjectPoster = project.ProjectPoster;
                        return View(convertedProject);
                    }


                    try
                    {
                        //rename the file
                        string upload =
                            "Project_" + convertedProject.ProjectId + "_Poster" + fileExtension;

                        //get the absolute file path to the images folder in the server
                        string saveFile =
                                Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", upload);

WEB2019Apr_P02_Team1/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="jumbotron">
    <h2 class="display-3">Welcome, @ViewData["StudentName"]!</h2>
    <img class="img-fluid" style="width:100%; height:600px;" src="~/images/StudentIndex.jpg" />
    <p class="lead">What will you like to do today?</p>
    <hr class="my-2" />
    <div class="d-flex">
        <div class="container">
            <h3>Student</h3>
            <p class="lead">Start Creating a Stunnng Profile! Remember to keep it updated!</p>
            <div style="margin:2px;">
                <a class="btn btn-info p-4" asp-controller="Student" asp-action="ViewProfile">View Profile</a>
                <a class="btn btn-info p-4" asp-controller="Student" asp-action="Update">Update</a>
                <a class="btn btn-info p-4" asp-controller="Student" asp-action="UploadPhoto">Upload a new photo</a>
                <a class="btn btn-info p-4" asp-controller="Student" asp-action="ViewSuggestions">View Suggestions</a>
            </div>
        </div>
        <div class="container">
            <h3>Project</h3>
            <p class="lead">Impress your employers with amazing projects! Let them know your talents!</p>
            <div style="margin:2px;">
                <a class="btn btn-success p-4" asp-controller="Project" asp-action="Index">Project Home</a>
                <a class="btn btn-success p-4" asp-controller="Project" asp-action="ViewProject">View Project</a>
                <a class="btn btn-success p-4" asp-controller="Project" asp-action="Create">Create a New Porject</a>
            </div>
        </div>
    </div>
</div>

WEB2019Apr_P02_Team1/Views/Student/Register.cshtml
@model WEB2019Apr_P02_Team1.Models.Student

@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/CommonForms.css" />

<div class="row justify-content-center form-wrapper">
    <div class="col-md-4">
        <h2>Register Student</h2>
        @if (ViewData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">@ViewData["Message"]</div>
        }
        @if (ViewData["Success"] != null)
        {
            <div class="alert alert-success" role="alert">@ViewData["Success"]</div>
        }
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course" class="control-label"></label>
                <select asp-for="Course" asp-items="@ViewData["CourseList"] as
                    List<SelectListItem>" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddr" class="control-label"></label>
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MentorID" class="control-label">Mentor</label>
                <select asp-for="MentorID" asp-items="@ViewData["LecturerNames"] as
                    List<SelectListItem>" class="form-control"></select>
            </div>
            <input type="submit" class="btn btn-primary" />
        </form>
    </div>
</div>

WEB2019Apr_P02_Team1/Views/Student/Update.cshtml
@model WEB2019Apr_P02_Team1.Models.ProfileViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/CommonForms.css" />

<div class="row justify-content-center form-wrapper">
    <div class="col-md-4">
        <h2>Update</h2>
        <h4>Student</h4>
        <hr />
        @if (ViewData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">@ViewData["Message"]</div>
        }
        @if (ViewData["Success"] != null)
        {
            <div class="alert alert-success" role="alert">@ViewData["Success"]</div>
        }
        <form asp-action="Update" asp-controller="Student">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" readonly class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course" class="control-label"></label>
                <input asp-for="Course" readonly class="form-control" />
                <span asp-validation-for="Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea rows="5" cols="50" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Achievement" class="control-label"></label>
                <textarea rows="3" cols="30" asp-for="Achievement" class="form-control"></textarea>
                <span asp-validation-for="Achievement" class="text-danger"></span>
            </div>
            <div class="form-group">
                @for (int i = 0; i < Model.SkillSetList.Count; i++)
                {
                    <label asp-for="SkillSetList[i].IsChecked">
                        @Model.SkillSetList[i].SkillSetName
                    </label>
                    if (Model.SkillSetList[i].IsChecked)
                    {
                        <input asp-for="SkillSetList[i].IsChecked" type="checkbox" checked />
                    }
                    else
                    {
                        <input asp-for="SkillSetList[i].IsChecked" type="checkbox" />
                    }
                    <input asp-for="SkillSetList[i].SkillSetID" type="hidden" />
                    <input asp-for="SkillSetList[i].SkillSetName" type="hidden" />
                }
            </div>
            <div class="form-group">
                <label asp-for="ExternalLink" class="control-label"></label>
                <input asp-for="ExternalLink" class="form-control" />
                <span asp-validation-for="ExternalLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddr" class="control-label"></label>
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr" class="text-danger"></span>
            </div>
            <input type="submit" value="Save" class="btn btn-primary" />
            <div>
                <a class="btn btn-warning" asp-action="Index">Back to Home</a>
            </div>
        </form>
    </div>
</div>
<br />

WEB2019Apr_P02_Team1/Views/Student/UploadPhoto.cshtml
@model WEB2019Apr_P02_Team1.Models.Student

@{
    ViewData["Title"] = "UploadPhoto";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int rand = new Random().Next(0, 999999);
}

<link rel="stylesheet" href="~/css/CommonForms.css" />

<div class="row justify-content-center form-wrapper">
    <div class="col-sm-8 col-md-6 col-lg-4">
        <h2>Upload Profile Picture</h2>
        <h4>Student</h4>
        <hr />
        @if (ViewData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">@ViewData["Message"]</div>
        }
        @if (ViewData["Success"] != null)
        {
            <div class="alert alert-success" role="alert">@ViewData["Success"]</div>
        }
        <img src="~/images/@Model.Photo?dummy=@rand" class="img-thumbnail" />
        <form asp-action="UploadPhoto" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FileToUpload" class="font-weight-bold"></label>
                <br />
                <input asp-for="FileToUpload" accept="image/jpeg" />
                <input asp-for="StudentID" type="hidden" />
                <input asp-for="Name" type="hidden" />
                <input asp-for="Photo" type="hidden" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

WEB2019Apr_P02_Team1/Views/Student/ViewProfile.cshtml
@model WEB2019Apr_P02_Team1.Models.ProfileViewModel

@{
    ViewData["Title"] = "ViewProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int rand = new Random().Next(0, 999999);
}

<h2>ViewProfile</h2>
<h4>Student</h4>
<hr />
<div class="container">
    <div class="row">
        <img class="col-12 col-sm-12 col-md-5 col-lg-5" src="~/images/@Model.Photo?dummy=@rand" />
        <div class="col-12 col-sm-12 col-md-1 col-lg-1"></div>
        <div class="col-12 col-sm-12 col-md-4 col-lg-4">
            <dl>
                <dt>
                    <label asp-for="Name"></label>
                </dt>
                <dd>
                    @Html.Display("Name")
                </dd>
                <dt>
                    <label asp-for="Course"></label>
                </dt>
                <dd>
                    @Html.Display("Course")
                </dd>
                <dt>
                    <label asp-for="Achievement"></label>
                </dt>
                <dd>
                    @Html.Display("Achievement")
                </dd>
                <dt>
                    <label asp-for="SkillSetList"></label>
                </dt>
                @foreach (var item in Model.SkillSetList)
                {
                    <dd>@item.SkillSetName</dd>
                }
                <dt>
                    <label asp-for="ExternalLink"></label>
                </dt>
                <dd>
                    <a href="@Html.Display("ExternalLink")">@Html.Display("ExternalLink")</a>
                </dd>
                <dt>
                    <label asp-for="EmailAddr"></label>
                </dt>
                <dd>
                    @Html.Display("EmailAddr")
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <label class="font-weight-bold" asp-for="Description"></label>
            <p>
                @Html.Display("Description")
            </p>
        </div>
    </div>
</div>

WEB2019Apr_P02_Team1/Views/Student/ViewSuggestions.cshtml
@model IEnumerable<WEB2019Apr_P02_Team1.Models.Suggestion>

@{
    ViewData["Title"] = "ViewSuggestions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <h2 class="text-center">ViewSuggestions</h2>
</p>

@if (TempData["Message"] != null)
{
    <div class="alert alert-danger" role="alert">@TempData["Message"]</div>
}
else if(TempData["Success"] != null)
{
    <div class="alert alert-success" role="alert">@TempData["Success"]</div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                No.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th class="font-weight-bold">
                Options
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach ((var item, int index) in Model.Select((suggestion, index) => (suggestion, index)))
        {
            <tr>
                <td>
                    @(index+1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @if (item.Status == 'Y')
                    {
                        <button class="btn btn-success" type="button" disabled>Acknowledge</button>
                    }
                    else
                    {
                        <div class="btn btn-success">
                            <a asp-action="Acknowledge" asp-controller="Student" asp-route-id="@item.SuggestionID"
                               style="text-decoration:none; color:white;">Acknowledge</a>
                        </div>
                    }
                    <button class="btn btn-info" type="button" data-toggle="modal" data-target="#modal-@index">
                        View
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@foreach((var item, int index) in Model.Select((suggestion, index) => (suggestion, index)))
{
    <div class="modal" id="modal-@index" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="flex flex-column">
                        <h4 class="modal-title">Suggestions</h4>
                        <p style="margin: 0;">Date Created: @item.DateCreated</p>
                        <p style="margin: 0;">Acknowledge Status: @item.Status</p>
                    </div>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    @item.Description
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}