WEB2019Apr_P02_Team1/Controllers/DebugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WEB2019Apr_P02_Team1.Models;
using WEB2019Apr_P02_Team1.DAL;

namespace WEB2019Apr_P02_Team1.Controllers
{
    public class DebugController : Controller
    {
        private LecturerDAL lecturerContext = new LecturerDAL();
        private StudentDAL studentContext = new StudentDAL();
        private SuggestionDAL suggestionContext = new SuggestionDAL();

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult DebugViewLecturers()
        {
            List<Lecturer> lecturers = lecturerContext.GetAll();
            return View(lecturers);
        }

        public ActionResult DebugViewStudents()
        {
            List<Student> students = studentContext.GetAllStudents();
            return View(students);
        }

        public ActionResult DebugViewSuggestions()
        {
            List<Suggestion> suggestions = suggestionContext.GetAll();
            return View(suggestions);
        }
    }
}

WEB2019Apr_P02_Team1/Views/Debug/DebugViewLecturers.cshtml
@model IEnumerable<WEB2019Apr_P02_Team1.Models.Lecturer>

@{
    ViewData["Title"] = "DebugViewLecturers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DebugViewLecturers</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LecturerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LecturerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WEB2019Apr_P02_Team1/Views/Debug/DebugViewStudents.cshtml
@model IEnumerable<WEB2019Apr_P02_Team1.Models.Student>

@{
    ViewData["Title"] = "DebugViewStudents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DebugViewStudents</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Achievement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExternalLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MentorID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Photo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Achievement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExternalLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MentorID)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WEB2019Apr_P02_Team1/Views/Debug/DebugViewSuggestions.cshtml
@model IEnumerable<WEB2019Apr_P02_Team1.Models.Suggestion>

@{
    ViewData["Title"] = "DebugViewSuggestions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DebugViewSuggestions</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SuggestionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LecturerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SuggestionID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LecturerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

WEB2019Apr_P02_Team1/Views/Debug/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Debug Index</h2>

<h4>Lecturer</h4>
<a asp-controller="Lecturer" asp-action="Login">Login</a>
<br />
<a asp-controller="Lecturer" asp-action="Register">Register</a>
<br />
<a asp-controller="Lecturer" asp-action="PostSuggestion">Post Suggestion</a>
<br />
<a asp-controller="Lecturer" asp-action="ViewSuggestions">View Suggestions</a>
<br />
<a asp-controller="Lecturer" asp-action="ViewMentees">View Mentees</a>
<br />
<a asp-controller="Lecturer" asp-action="UpdateProfile">Update Profile</a>
<br /><br />

<h4>Debug</h4>
<a asp-controller="Debug" asp-action="DebugViewLecturers">View All Lecturers</a>
<br />
<a asp-controller="Debug" asp-action="DebugViewStudents">View All Students</a>
<br />
<a asp-controller="Debug" asp-action="DebugViewSuggestions">View All Suggestions</a>
<br />
<a asp-controller="Home" asp-action="Logout">Logout</a>